name: DynamicPerformance
version: 1.0.0
main: com.itzlynx197.dynamicperformance.DynamicPerformancePlugin
api-version: 1.21
authors:
  - itz_lynx197
description: An advanced Minecraft server optimization plugin for 1.21.x
softdepend: []

commands:
  dp:
    description: Admin commands for Dynamic PERFORMANCE+
    usage: /dp <subcommand>
    permission: dynamicperformance.admin